export type UserListData = { name: string; username: string };

export const firstYearUsers: UserListData[] = [
  { name: "Ishika Gupta", username: "ishika2609" },
  { name: "Pushpesh Srivastava", username: "Balji1104" },
  { name: "Palash Soni", username: "Palash_soni" },
  { name: "Om Jethava", username: "omjethva24" },
  { name: "Gaurav Maurya", username: "GauravMaurya07" },
  { name: "Shatakshi Singh", username: "shatakshi07777" },
  { name: "Kant Yanvi Rajendrakumar", username: "yanvi_kant" },
  { name: "Shreya Yadav", username: "ShreyaYadav26" },
  { name: "Rohit Yadav", username: "Rohityadavv324" },
  { name: "Asparsh Raj", username: "asparsh19" },
  { name: "Vijaya Kumari Mina", username: "vijayamina" },
  { name: "Basant Kumar", username: "basantkumar66972" },
  { name: "Supriya Gupta", username: "Supriya_Gupta1744" },
  { name: "Atul Sharma", username: "PQttVHca2P" },
  { name: "Anand Saxena", username: "AnandSaxena" },
  { name: "Aditi Barman", username: "adtbrmn" },
  { name: "Subham Patra", username: "Subhampatra1916" },
  { name: "Abhishek Gupta", username: "Abhishek-Gupta" },
  { name: "Aaron Dourado", username: "douradoaaron" },
  { name: "Shivang Garg", username: "shivang-garg" },
  { name: "Sushant", username: "Sushantrajput80" },
  { name: "Shikhar Asthana", username: "Shikhar_asthana23" },
  { name: "Yash Kumar Tiwari", username: "_tiwariyash" },
  { name: "Yashika", username: "Yashika_bajaj09" },
  { name: "Mayank Rajpoot", username: "Mayank_rajpoot534" },
  { name: "Omesh Choudhary", username: "omesh_choudhary" },
  { name: "Shailendra Patidar", username: "Shailendra_patidar" },
  { name: "Kumar Roy", username: "Kumar_Roy8695" },
  { name: "Parv Chetwani", username: "parvchetwani12" },
  { name: "Arpit Singh", username: "Arpit_Singh_05" },
  { name: "Aadarsh Dharmadhikari", username: "aadarsh_deo" },
  { name: "Ranjan Kumar Patra", username: "Ranjan_Kumar_Patra" },
  { name: "Ritika Pamnani", username: "ritikaaaaaaa" },
  { name: "Sheetal Yadav", username: "Sheetal906" },
  { name: "Shivanshu Verma", username: "4n3isWD2NA" },
  { name: "Ritik Gupta", username: "ritikgupta_118" },
  { name: "Mishri Lal Patel", username: "ml_patel88" },
  { name: "Prateek Dubey", username: "Prateekdubey_1105" },
  { name: "Neha Pamnani", username: "Neha_Pamnani" },
  { name: "Arjun Saini", username: "arjunsaini01" },
  { name: "Ankit Parmar", username: "ankitparmar2003" },
  { name: "Sazal Thakur", username: "Sazal_thakur" },
  { name: "Aayush Pratap Singh Shishodia", username: "shishodiaaayush819" },
  { name: "Niharika Jain", username: "Niharika_jain123" },
  { name: "Abhinav Rai", username: "navil8858" },
  { name: "Vikesh Ray", username: "bvdwffEqPt" },
  { name: "Sushant Kujur", username: "a76PrvuHKw" },
  { name: "Amit Prajapati", username: "amit_prajapati_62" },
  { name: "Harshita Mishra", username: "hersheyyydotm" },
  { name: "Manu Singh", username: "manu-120" },
  { name: "Keshav", username: "KeshavTiwari80" },
  { name: "Astitv Gupta", username: "astitvgupta" },
  { name: "Durgesh Pandey", username: "mrdurgeshpandey1111" },
  { name: "Ravi Kumar Jaiswal", username: "Ravi_kumar234" },
  { name: "Saumya Dhamde", username: "jRa2cqCpzf" },
  { name: "Akshat Kushwaha", username: "Dev_Akshat24" },
  { name: "Gourav Khandelwal", username: "Gourav_2905" },
  { name: "Namyank Gupta", username: "Namyank" },
  { name: "Sushant Kumar Jha", username: "David_Bharadwaj" },
  { name: "Om Prakash Sahu", username: "Om-Prakash23" },
  { name: "Anshul Khandelwal", username: "Anshul_750" },
  { name: "Shubham Kumar", username: "sbm39" },
  { name: "Ankit Kumar", username: "Ankitkumar210" },
  { name: "Harsh Pandey", username: "Harshh_pandeyy" },
  { name: "Abhay Prasad", username: "Abhay_Prsd" },
  { name: "Khushi Saini", username: "Khushi1095" },
  { name: "Sumit Kumar", username: "Sumit7237" },
  { name: "Tanu Saini", username: "Tanu0202" },
  { name: "Avnish Rajkumar Yadav", username: "avnishxcode" },
  { name: "Aditya Kumar", username: "i8fwk2nCzf" },
  { name: "Aryan Singh", username: "ryanncodes" },
  { name: "Aditya Malviya", username: "Aditya0443" },
  { name: "Hamda Laeeq", username: "Hamda_Laeeq123" },
  { name: "Shubham Saumendra Kumar", username: "shubhsbk31" },
  { name: "Ravi", username: "Anoy001" },
  { name: "Md Ayaz", username: "jxER0faqgz" },
  { name: "Riddhi Khilnani", username: "RiddhiKhilnani" },
  { name: "Gargi Yadav", username: "Gargi_yadav" },
  { name: "Harshit Beniwal", username: "HarshitBeniwal7310" },
  { name: "Gaurav Toriya", username: "Gaurav_9058" },
  { name: "Yuvraj Sachan", username: "yuvrajsac15-source" },
  { name: "Sachin Kumar", username: "Sachin_kumar09" },
  { name: "Ankit Dangi", username: "ankit_dangi07" },
  { name: "Abhishek Kumar", username: "Abhishek10847" },
  { name: "Devang Kesarwani", username: "devkes2005" },
  { name: "Piyush Verma", username: "piiiyusssh" },
  { name: "Rajwardhan Panwar", username: "Rajwardhan454" },
  { name: "Aryan Kumar", username: "Aksagar007" },
  { name: "Aditya Kumar Verma", username: "Adiprogrammer73" },
  { name: "Mayank Saiyam", username: "Mayank_Saiyam" },
  { name: "Abhishek Kumar Bharti", username: "Abhishekbhartidev" },
  { name: "Reshmi", username: "Reshmileet" },
  { name: "Shraddha Yadav", username: "1rtR6w80fg" },
  { name: "Raja Singh Solanki", username: "_rajasinghsolanki9" },
  { name: "Malle Mahitha Sri", username: "2300520033" },
  { name: "Mahima", username: "MAHIIMA07" },
  { name: "Vipin Yadav", username: "Vipinyadav001" },
  { name: "Mantasha Khan", username: "mantasha_256" },
  { name: "Priyanshi Kumari", username: "Priyanshi_Kumari20" },
  { name: "Vishal Singh", username: "Vishal9211" },
  { name: "Piyush Kr Pathak", username: "bumbumss" },
  { name: "Vandna Patidar", username: "Vandnapatidar" },
  { name: "Sidant Meena", username: "sid189" },
  { name: "Sunil Kumawat", username: "skumawat_" },
  { name: "Ameen Khan", username: "ameen189" },
  { name: "Amar Kumar", username: "Amar__2004" },
  { name: "Anjikya Vinay", username: "anjikyavinay" },
  { name: "Saraswati Dhakad", username: "saraswati_111" },
  { name: "Sumant Kumar Gond", username: "EmlujWnis2" },
];

export const secondYearUsers: UserListData[] = [
  { name: "Nikhil Idiculla", username: "LiKh1n" },
  { name: "Akarshan Pathak", username: "Akarshan_pathak" },
  { name: "Ram Sankar S", username: "RamSankarS" },
  { name: "Baibhaw Agarwal", username: "Baibhav_Agarwal" },
  { name: "Sumit Goswami", username: "sumitgoswami0902" },
  { name: "Yash Gupta", username: "_Yash_gupta_05" },
  { name: "Sahil Mishra", username: "sahilmishraa_" },
  { name: "Chandrika Patidar", username: "chandrika_patidar" },
  { name: "Shiwangi Priya", username: "SPSR_08" },
  { name: "Anshu Kumar Mishra", username: "Anshu666" },
  { name: "Shaurya Kajla", username: "JAI_RAJPUTANA" },
  { name: "Banoth Shiva", username: "banothshiva" },
  { name: "Sumit Patel", username: "Sumit_Patel_MANIT" },
  { name: "Abhijeet Singh Dhillon", username: "AviDhillon" },
  { name: "Apoorv Trivedi", username: "Apoorv_Trivedi" },
  { name: "Manish Kumar", username: "Manish_Kumar_150" },
  { name: "Kartik Gupta", username: "Kartik__gupta__" },
  { name: "Likhit Rajendra Meshram", username: "Yytgq17NLy" },
  { name: "Prabhakar Kant Kuldeep", username: "Prabhakarkant" },
  { name: "Altaf Raja", username: "eisen_bear__" },
  { name: "Appurvi Garg", username: "Appurvi_garg" },
  { name: "Mukul Dev Singh", username: "Mukul_1903" },
  { name: "Ravi Kumar Mahto", username: "Ravihzb" },
  { name: "Mohit Singh Rajput", username: "mohit_rajput207" },
  { name: "Mythili Raj K K", username: "MythiliRajKK" },
  { name: "Sumit Sahai", username: "s7mit_03" },
  { name: "Dinesh Saini", username: "dineshsaini_" },
  { name: "Abhay Kodape", username: "Abhay_Kodape" },
  { name: "Sindhuja Kumari", username: "Sindhuja_Kumari" },
  { name: "Shatadal Das", username: "shatadal__das" },
  { name: "Vishali", username: "Vishali_Banga" },
  { name: "Bhavishya Sisodiya", username: "Bhavishya_12" },
  { name: "Shivam Singh", username: "ShivamSingh_126" },
  { name: "Geet Madhyam", username: "Geet_Madhyam" },
  { name: "Sipu Swain", username: "sipuswain" },
  { name: "Robin Poonia", username: "robin_poonia" },
  { name: "Hardik Katiyar", username: "hardik2004Aa" },
  { name: "Pushpendra", username: "diwakar_123" },
  { name: "Pankaj Jangra", username: "COSMOS1" },
];

export const thirdYearUsers: UserListData[] = [
  { name: "Yash Bhatt", username: "yashbhatt4133" },
  { name: "Vatsal Daxesh Vakharia", username: "vatsal_4802" },
  { name: "Mukul Dixit", username: "Mukul_1608" },
  { name: "Avinash Chaturvedi", username: "avinashchaturvedi2002" },
  { name: "Sanjeet Soni", username: "sanjeet_soni" },
  { name: "Siddharth Kumar", username: "sid_113" },
  { name: "Lavish Dabur", username: "lavishdabur" },
  { name: "Anshul Daksh", username: "anshul_daksh_009" },
  { name: "Ayush Gupta", username: "ayusome" },
  { name: "Sachin Jha", username: "sachin_rodies" },
];