export type UserListData = { name: string; username: string };

export const firstYearUsers: UserListData[] = [
  { name: "Nikhil Idiculla", username: "LiKh1n" },
  { name: "Akarshan Pathak", username: "Akarshan_pathak" },
  { name: "Ram Sankar S", username: "RamSankarS" },
  { name: "Baibhaw Agarwal", username: "Baibhaw_25" },
  { name: "Sumit Goswami", username: "sumitgoswami0902" },
  { name: "Yash Gupta", username: "_Yash_gupta_05" },
  { name: "Sahil Mishra", username: "sahilmishraa_" },
  { name: "Chandrika Patidar", username: "chandrika_patidar" },
  { name: "Shiwangi Priya", username: "SPSR_08" },
  { name: "Anshu Kumar Mishra", username: "anshu777" },
  { name: "Shaurya Kajla", username: "SK_DESTROYER" },
  { name: "Banoth Shiva", username: "banothshiva" },
  { name: "Sumit Patel", username: "Sumit_Patel_MANIT" },
  { name: "Abhijeet Singh Dhillon", username: "AviDhillon" },
  { name: "Apoorv Trivedi", username: "Apoorv_Trivedi" },
  { name: "Manish Kumar", username: "Manish_Kumar_150" },
  { name: "Kartik Gupta", username: "Kartik__gupta__" },
  { name: "Likhit Rajendra Meshram", username: "Yytgq17NLy" },
  { name: "Prabhakar Kant Kuldeep", username: "Prabhakarkant" },
  { name: "Altaf Raja", username: "eisen_bear__" },
  { name: "Appurvi Garg", username: "Appurvi_garg" },
  { name: "Mukul Dev Singh", username: "Mukul_1903" },
  { name: "Ravi Kumar Mahto", username: "Ravihzb" },
  { name: "Mohit Singh Rajput", username: "mohit_rajput207" },
  { name: "Mythili Raj K K", username: "MythiliRajKK" },
  { name: "Sumit Sahai", username: "s7mit_03" },
  { name: "Dinesh Saini", username: "dineshsaini_" },
  { name: "Abhay Kodape", username: "Abhay_Kodape" },
  { name: "Sindhuja Kumari", username: "Sindhuja_Kumari" },
  { name: "Shatadal Das", username: "Shatadal_Das" },
  { name: "Vishali", username: "Vishali_Banga" },
  { name: "Bhavishya Sisodiya", username: "Bhavishya_12" },
  { name: "Shivam Singh", username: "ShivamSingh_126" },
];

export const secondYearUsers: UserListData[] = [
  { name: "Li Hao", username: "lee215" },
  { name: "Andrew Wice", username: "awice" },
  { name: "Wisdom Peak", username: "wisdompeak" },
  { name: "Stefan Pochmann", username: "StefanPochmann" },
  { name: "Yashar", username: "yashar" },
  { name: "Votrubac", username: "votrubac" },
  { name: "Fisher Coder", username: "fishercoder" },
  { name: "Huahua", username: "huahua" },
  { name: "Rock", username: "rock" },
  { name: "WalkCCC", username: "walkccc" },
  { name: "Alex Yu", username: "alexander-yu" },
  { name: "NeetCode", username: "neetcode" },
  { name: "Sean Prashad", username: "SeanPrashad" },
  { name: "Kevin Naughton", username: "KevinNaughtonJr" },
  { name: "Errichto", username: "errichto" },
  { name: "DBabichev", username: "dbabichev" },
  { name: "Tushar Roy", username: "tusharroy25" },
  { name: "Mission Peace", username: "mission-peace" },
  { name: "Kumar Gaurav", username: "kumar-gaurav" },
  { name: "Ye15", username: "ye15" },
];

export const thirdYearUsers: UserListData[] = [
  { name: "LeetCode Official", username: "leetcode" },
  { name: "Zhengyang", username: "zhengyang2015" },
  { name: "Shivam Gupta", username: "shivamgupta" },
  { name: "Jingwei Li", username: "jingweili" },
  { name: "Justin Chen", username: "justinchen" },
  { name: "Akshay Rajput", username: "akshayrajput" },
  { name: "Min Cost Max Flow", username: "mincostmaxflow" },
  { name: "Siyang Yuan", username: "siyangyuan" },
  { name: "Yangshun Tay", username: "yangshun" },
  { name: "Coding Simplified", username: "codingsimplified" },
  { name: "LC Solution", username: "lcsolution" },
  { name: "Abhinav Gupta", username: "abhinavgupta" },
  { name: "Harshit Gupta", username: "harshitgupta" },
  { name: "AlgoMonster", username: "algomonster" },
  { name: "CodeWithMik", username: "codewithmik" },
  { name: "Ankit Kumar", username: "ankitkumar" },
  { name: "Rishabh Mishra", username: "rishabhmishra" },
  { name: "Dynamic Programming", username: "dynamicprogramming" },
  { name: "Binary Search", username: "binarysearch" },
  { name: "Graph Theory", username: "graphtheory" },
];
