export const leetCodeUsernames: { name: string; username: string }[] = [
  { name: "Nikhil Idiculla", username: "LiKh1n" },
  { name: "Akarshan Pathak", username: "Akarshan_pathak" },
  { name: "Ram Sankar S", username: "RamSankarS" },
  { name: "BAIBHAW AGARWAL", username: "Baibhaw_25" },
  { name: "Sumit Goswami", username: "sumitgoswami0902" },
  { name: "Yash Gupta", username: "_Yash_gupta_05" },
  { name: "Sahil Mishra", username: "sahilmishraa_" },
  { name: "CHANDRIKA PATIDAR", username: "chandrika_patidar" },
  { name: "Shiwangi Priya", username: "SPSR_08" },
  { name: "Anshu Kumar Mishra", username: "anshu777" },
  { name: "Shaurya kajla", username: "SK_DESTROYER" },
  { name: "BANOTH SHIVA", username: "banothshiva" },
  { name: "Sumit Patel", username: "Sumit_Patel_MANIT" },
  { name: "Abhijeet Singh Dhillon", username: "AviDhillon" },
  { name: "Apoorv Trivedi", username: "Apoorv_Trivedi" },
  { name: "Manish Kumar", username: "Manish_Kumar_150" },
  { name: "Kartik Gupta", username: "Kartik__gupta__" },
  { name: "Sumit Sahai", username: "yeahitsdevil" },
  { name: "Likhit Rajendra Meshram", username: "Yytgq17NLy" },
  { name: "Prabhakar Kant kuldeep", username: "Prabhakarkant" },
  { name: "Altaf Raja", username: "eisen_bear" },
  { name: "Appurvi Garg", username: "Appurvi_garg" },
  { name: "Mukul Dev Singh", username: "Mukul_1903" },
  { name: "Ravi Kumar mahto", username: "Ravihzb" },
  { name: "Mohit singh Rajput", username: "mohit_rajput207" },
  { name: "Mythili Raj K K", username: "MythiliRajKK" },
  { name: "Sumit Sahai", username: "s7mit_03" },
  { name: "Dinesh Saini", username: "dineshsaini_" },
  { name: "Abhay Kodape", username: "Abhay_Kodape" },
  { name: "Sindhuja Kumari", username: "Sindhuja_Kumari" },
  { name: "Shatadal Das", username: "Shatadal_Das" },
  { name: "VISHALI", username: "Vishali_Banga" },
  { name: "Bhavishya sisodiya", username: "Bhavishya_12" },
  { name: "Shivam Singh", username: "ShivamSingh_126" },
];
